# Generated by Django 5.1.7 on 2025-04-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fort',
            new_name='Adj',
        ),
    ]
