# Generated by Django 5.1.7 on 2025-04-01 10:10
# And edited by cuc on 2025-04-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
                ('title', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('text', models.TextField()),
            ],
        ),
    ]

