# Generated by Django 4.2.20 on 2025-04-15 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_user_first_name_alter_user_last_name_and_more'),
        ('forts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fort',
            name='user',
        ),
        migrations.AlterField(
            model_name='fort',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forts/static/images/'),
        ),
        migrations.AlterField(
            model_name='fort',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('meet_place', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('count', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
            ],
        ),
    ]
