# Generated by Django 5.1.7 on 2025-04-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forts', '0002_alter_fort_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('meet_place', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('count', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
