# Generated by Django 5.1.7 on 2025-04-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forts', '0005_alter_fort_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fort',
            name='image',
            field=models.ImageField(upload_to='forts/'),
        ),
    ]
