# Generated by Django 5.1.7 on 2025-04-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forts', '0006_alter_fort_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fort',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forts/static/images/'),
        ),
    ]
