# Generated by Django 4.2.20 on 2025-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forts', '0007_alter_fort_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='client_id',
            field=models.BigIntegerField(default=''),
        ),
    ]
