# Generated by Django 4.2.20 on 2025-04-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_user_first_name_alter_user_last_name_and_more'),
        ('forts', '0011_alter_excursion_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user'),
        ),
    ]
