# Generated by Django 4.2.20 on 2025-04-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forts', '0012_alter_excursion_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='client_id',
            new_name='client',
        ),
    ]
