# Generated by Django 4.2.20 on 2025-04-13 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_user_first_name_alter_user_last_name_and_more'),
        ('forts', '0013_rename_client_id_excursion_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='client',
        ),
        migrations.AddField(
            model_name='excursion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.user'),
        ),
    ]
