# Generated by Django 4.2.20 on 2025-04-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forts', '0016_alter_excursion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='user',
        ),
    ]
